version: '3.3'
services:
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - type: volume
        source: ./api/
        target: /api
    working_dir: /api
    entrypoint:
      - "/api/entrypoint.sh"
  front:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - type: volume
        source: ./front/
        target: /front
    working_dir: /front
    environment:
      - HOST=0.0.0.0
      - PORT=8083
    entrypoint:
      "/front/entrypoint.sh"
