version: '3.3'
services:
  newapi:
    build:
      context: ./newapi/
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./newapi:/newapi
    working_dir: /newapi
    entrypoint:
      - "/newapi/entrypoint.sh"
    environment:
      - CONFIGS_PATH=/newapi/config/
      - RESOURCES_PATH=/newapi/resources/
    networks:
      - newapi
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./api:/api
    working_dir: /api
    entrypoint:
      - "/api/entrypoint.sh"
    environment:
      - CONFIGS_PATH=/api/config/
      - RESOURCES_PATH=/api/resources/
    networks:
      - api
  front:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
    working_dir: /front/
    volumes: 
     - ./front:/front
    ports:
      - "8083:8083"
    environment:
      - HOST=0.0.0.0
      - PORT=8083
    entrypoint:
      "/front/entrypoint.sh"
  db:
    image: postgres
    ports:
      - "8432:5432"
    networks:
      - api
      - newapi
    environment:
      - POSTGRES_DB=keybr
      - db_pgdata:var/lib/postgresql/data
volumes:
  front:
  db_pgdata:
networks:
  newapi:
  api:
