version: '3.3'
services:
  api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./api:/api
    working_dir: /api
    entrypoint:
      - "/api/entrypoint.sh"
  front:
    build:
      context: ./front/
      dockerfile: ./Dockerfile
    working_dir: /front/
    volumes: 
     - ./front:/front
    ports:
      - "8083:8083"
    environment:
      - HOST=0.0.0.0
      - PORT=8083
    entrypoint:
      "/front/entrypoint.sh"
volumes:
  front:
